spring.application.name=course
server.port=8081

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5434/coursedb
spring.datasource.username=postgres
spring.datasource.password=password123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=S3cur3SuperLongSecretKeyForEduTrackApp2024!MustBe32CharsMin
app.jwt.expiration-ms=86400000

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=method
